name = "my-it-support-site"
main = "workers-site/index.js"
account_id = "7bb2a28ac72e0115ba6377b8597014f2"
compatibility_date = "2025-07-16"

[site]
bucket = "./"  # Serve your static files from the project root
